### ISSUE TITLE
Update to the latest subsquid-network-transport

### ISSUE THREAD

**Issue by kalabukdima** [subsquid/query-gateway#2]
If the dependency versions are updated, this error occurs during the start: https://github.com/Wiezzel/rust-libp2p/blob/subsquid/transports/tls/src/lib.rs#L80
```
Server cert key DER is valid; qed
```

**Comment by kalabukdima** [comment]
The issue is reproduced when `rustls` updates from `v0.23.10` to `v0.23.12`. Since the dependency version is not fixed, it can happen any time while dealing with dependencies (e.g., if you call `cargo update`).
As long as the lock file is in place, it should be fine.

**Comment by Wiezzel** [comment]
This is related: https://github.com/libp2p/rust-libp2p/issues/5487
